"""Turns AI hero art in art-source/ into web-ready files for the site.

Put one image per hero in art-source/, named by its slug (e.g. juggernaut.png; see art/PROMPTS.md),
then run:  python tools/prepare_art.py

For each image it writes, centre-cropped to 2:3:
  public/art/<slug>.webp        720x1080, used on the tarot cards and posters
  public/art/thumb/<slug>.webp  240x360,  used in the hero picker
and rewrites public/art/manifest.js with the list of heroes that have art.
Needs Pillow:  pip install pillow
"""
import re
import sys
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "art-source"
OUT = ROOT / "public" / "art"
SIZES = {OUT: (720, 1080, 84), OUT / "thumb": (240, 360, 80)}

data = (ROOT / "public" / "js" / "data.js").read_text(encoding="utf-8")
SLUGS = {slug for slug in re.findall(r'\["[^"]+", "([a-z0-9_]+)", "(?:str|agi|int|uni)"', data)}


def main():
    if not SRC.is_dir():
        sys.exit(f"Create {SRC} and put the hero images in it first.")
    for d in SIZES:
        d.mkdir(parents=True, exist_ok=True)

    done, unknown = 0, []
    for path in sorted(SRC.iterdir()):
        if path.suffix.lower() not in {".png", ".jpg", ".jpeg", ".webp"}:
            continue
        slug = path.stem.lower()
        if slug not in SLUGS:
            unknown.append(path.name)
            continue
        with Image.open(path) as img:
            img = ImageOps.exif_transpose(img).convert("RGB")
            for d, (w, h, quality) in SIZES.items():
                ImageOps.fit(img, (w, h), Image.LANCZOS, centering=(0.5, 0.45)).save(d / f"{slug}.webp", "WEBP", quality=quality)
        done += 1

    have = sorted(p.stem for p in OUT.glob("*.webp") if p.stem in SLUGS and (OUT / "thumb" / p.name).exists())
    (OUT / "manifest.js").write_text(
        "// Generated by tools/prepare_art.py: heroes that have original art in public/art/.\n"
        f"const HERO_ART = new Set({have!r});\n".replace("'", '"'),
        encoding="utf-8",
    )
    print(f"Prepared {done} image(s). {len(have)}/{len(SLUGS)} heroes now have art.")
    if unknown:
        print("Skipped (file name isn't a hero slug, see art/PROMPTS.md):", ", ".join(unknown))
    missing = sorted(SLUGS - set(have))
    if missing and len(missing) <= 20:
        print("Still missing:", ", ".join(missing))


if __name__ == "__main__":
    main()
